import jsPDF from 'jspdf'

export const generateBiasReport = (biasMetrics, fileName) => {
  const doc = new jsPDF()
  
  // Header
  doc.setFillColor(59, 130, 246)
  doc.rect(0, 0, 210, 40, 'F')
  doc.setTextColor(255, 255, 255)
  doc.setFontSize(24)
  doc.text('BiasScan AI Report', 20, 25)
  doc.setFontSize(12)
  doc.text('Bias Detection Analysis', 20, 33)
  
  // Reset text color
  doc.setTextColor(0, 0, 0)
  
  // File info
  doc.setFontSize(10)
  doc.text(`File: ${fileName}`, 20, 50)
  doc.text(`Date: ${new Date().toLocaleDateString()}`, 20, 56)
  doc.text(`Total Rows: ${biasMetrics.totalRows}`, 20, 62)
  
  // Overall Risk
  doc.setFontSize(16)
  doc.text('Overall Risk Assessment', 20, 75)
  doc.setFontSize(12)
  
  const riskColor = biasMetrics.overallRisk === 'High' ? [239, 68, 68] : 
                    biasMetrics.overallRisk === 'Medium' ? [251, 191, 36] : 
                    [34, 197, 94]
  doc.setTextColor(...riskColor)
  doc.text(`Risk Level: ${biasMetrics.overallRisk}`, 20, 85)
  doc.setTextColor(0, 0, 0)
  
  // Detected Biases
  let yPos = 100
  doc.setFontSize(16)
  doc.text('Detected Biases', 20, yPos)
  yPos += 10
  
  biasMetrics.biases.forEach((bias, index) => {
    if (yPos > 270) {
      doc.addPage()
      yPos = 20
    }
    
    doc.setFontSize(14)
    doc.text(`${index + 1}. ${bias.type}`, 20, yPos)
    yPos += 8
    
    doc.setFontSize(10)
    doc.text(`Risk Level: ${bias.riskLevel}`, 25, yPos)
    yPos += 6
    
    // Distribution
    doc.text('Distribution:', 25, yPos)
    yPos += 6
    Object.entries(bias.distribution).forEach(([key, value]) => {
      doc.text(`  ${key}: ${value}${typeof value === 'number' && value < 100 ? '%' : ''}`, 30, yPos)
      yPos += 5
    })
    yPos += 2
    
    // Recommendation
    doc.setFont(undefined, 'bold')
    doc.text('Recommendation:', 25, yPos)
    doc.setFont(undefined, 'normal')
    yPos += 6
    const splitRec = doc.splitTextToSize(bias.recommendation, 160)
    doc.text(splitRec, 30, yPos)
    yPos += splitRec.length * 5 + 10
  })
  
  // Footer
  if (yPos > 250) {
    doc.addPage()
    yPos = 20
  }
  
  doc.setFontSize(10)
  doc.setTextColor(100, 100, 100)
  doc.text('Privacy Notice: This analysis was performed client-side.', 20, yPos + 10)
  doc.text('No data was transmitted or stored on external servers.', 20, yPos + 16)
  doc.text('Generated by BiasScan AI - Certified Fair AI Tool', 20, yPos + 22)
  
  // Save
  doc.save(`biasscan-report-${Date.now()}.pdf`)
}